name: format

on:
  push:
    paths:
      - "**/*.typ"
  pull_request:
    paths:
      - "**/*.typ"

jobs:
  typstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@main

      - name: Install typstyle
        run: cargo binstall typstyle --no-confirm --locked

      - name: Run typstyle check
        id: fmt
        run: |
          if ! typstyle --check $(find . -name '*.typ'); then
            echo "not_formatted=true" >> $GITHUB_OUTPUT
          else
            echo "not_formatted=false" >> $GITHUB_OUTPUT
          fi

      - name: Warn about formatting
        if: steps.fmt.outputs.not_formatted == 'true'
        run: |
          echo "::warning file=.,title=Typstyle::Some files are not formatted. Run 'typstyle -i <file>' to fix."
